apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: hrm

spec:
  type: ClusterIP

  selector:
    app: employee-service

  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096